"""Add qa_pairs to Document model

Revision ID: 02131c8d15e7
Revises: 7ce2a5874a01
Create Date: 2024-09-02 11:49:38.404092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02131c8d15e7'
down_revision = '7ce2a5874a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qa_pairs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('qa_pairs')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
